// data.js — menu, translations, reviews. Exposes globals.
// Image URLs reference cafe39's public CDN (the source content the user pointed at).

const IMG = (path) =>
  `https://cafe39.vercel.app/images/${decodeURIComponent(path)}`;

const MENU = [
  {
    id: "coffee",
    icon: "☕",
    items: [
      { id: "c1", price: 20, img: IMG("coffee%2Fcafe-den.jpg"), names: { en: "Saigon Black Coffee", vi: "Cà phê đen Sài Gòn", zh: "西贡黑咖啡", ja: "サイゴン ブラックコーヒー", ko: "사이공 블랙커피", fr: "Café noir de Saïgon", ru: "Сайгонский чёрный кофе" }, notes: { en: "Bold, sweet, served over ice" } },
      { id: "c2", price: 20, img: IMG("coffee%2Fcafe-sua.jpg"), names: { en: "Saigon Milk Coffee", vi: "Cà phê sữa Sài Gòn", zh: "西贡炼乳咖啡", ja: "サイゴン ミルクコーヒー", ko: "사이공 연유커피", fr: "Café au lait de Saïgon", ru: "Сайгонский кофе с молоком" }, notes: { en: "Robusta + condensed milk" } },
      { id: "c3", price: 25, img: IMG("coffee%2Fcafe-muoi.jpg"), names: { en: "Salt Coffee", vi: "Cà phê muối", zh: "海盐咖啡", ja: "ソルトコーヒー", ko: "솔트 커피", fr: "Café au sel", ru: "Кофе с солью" }, notes: { en: "Hue specialty" }, highlight: "House signature" },
      { id: "c4", price: 25, img: IMG("coffee%2Fcafe-dua.jpg"), names: { en: "Coconut Coffee", vi: "Cà phê dừa", zh: "椰子咖啡", ja: "ココナッツコーヒー", ko: "코코넛 커피", fr: "Café à la noix de coco", ru: "Кокосовый кофе" }, highlight: "Local favorite" },
      { id: "c5", price: 30, img: IMG("coffee%2Fcafe-bo.jpg"), names: { en: "Avocado Coffee", vi: "Cà phê bơ", zh: "牛油果咖啡", ja: "アボカドコーヒー", ko: "아보카도 커피", fr: "Café à l'avocat", ru: "Кофе с авокадо" }, notes: { en: "Creamy, indulgent" }, highlight: "Most ordered" },
      { id: "c6", price: 20, img: IMG("coffee%2Fbac-xiu.jpg"), names: { en: "Bạc Xỉu", vi: "Bạc xỉu", zh: "白咖啡", ja: "バクシウ", ko: "박씨우", fr: "Bạc xỉu", ru: "Бакщиу" }, notes: { en: "Coffee with extra milk" } },
      { id: "c7", price: 25, img: IMG("coffee%2Fcacao.jpg"), names: { en: "Hot Cocoa", vi: "Ca cao", zh: "可可", ja: "ココア", ko: "코코아", fr: "Cacao", ru: "Какао" } },
    ],
  },
  {
    id: "milktea",
    icon: "🧋",
    items: [
      { id: "m1", price: 25, img: IMG("milk-tea%2Ftruyen-thong.jpg"), names: { en: "Traditional Milk Tea", vi: "Trà sữa truyền thống", zh: "传统奶茶", ja: "トラディショナル ミルクティー", ko: "전통 밀크티", fr: "Thé au lait traditionnel", ru: "Классический молочный чай" } },
      { id: "m2", price: 25, img: IMG("milk-tea%2Fgreen-tea.jpg"), names: { en: "Green Thai Milk Tea", vi: "Trà sữa thái xanh", zh: "泰式绿奶茶", ja: "グリーン タイミルクティー", ko: "그린 타이 밀크티", fr: "Thé au lait thaï vert", ru: "Зелёный тайский молочный чай" } },
      { id: "m3", price: 25, img: IMG("milk-tea%2Fred-tea.jpg"), names: { en: "Red Thai Milk Tea", vi: "Trà sữa thái đỏ", zh: "泰式红奶茶", ja: "レッド タイミルクティー", ko: "레드 타이 밀크티", fr: "Thé au lait thaï rouge", ru: "Красный тайский молочный чай" } },
      { id: "m4", price: 25, img: IMG("milk-tea%2Ftaro.jpg"), names: { en: "Taro Milk Tea", vi: "Trà sữa khoai môn", zh: "香芋奶茶", ja: "タロミルクティー", ko: "타로 밀크티", fr: "Thé au lait au taro", ru: "Молочный чай с таро" } },
      { id: "m5", price: 25, img: IMG("milk-tea%2Ftra-xanh.jpg"), names: { en: "Matcha Milk Tea", vi: "Trà sữa matcha", zh: "抹茶奶茶", ja: "抹茶ミルクティー", ko: "말차 밀크티", fr: "Thé au lait matcha", ru: "Молочный чай матча" } },
      { id: "m6", price: 25, img: IMG("milk-tea%2Fchocolate.jpg"), names: { en: "Chocolate Milk Tea", vi: "Trà sữa chocolate", zh: "巧克力奶茶", ja: "チョコレートミルクティー", ko: "초콜릿 밀크티", fr: "Thé au lait chocolat", ru: "Шоколадный молочный чай" } },
      { id: "m7", price: 25, img: IMG("milk-tea%2Fdau.jpg"), names: { en: "Strawberry Milk Tea", vi: "Trà sữa dâu", zh: "草莓奶茶", ja: "ストロベリーミルクティー", ko: "딸기 밀크티", fr: "Thé au lait à la fraise", ru: "Молочный чай с клубникой" } },
      { id: "m8", price: 25, img: IMG("milk-tea%2Fnhai.jpg"), names: { en: "Jasmine Milk Tea", vi: "Trà sữa nhài", zh: "茉莉奶茶", ja: "ジャスミンミルクティー", ko: "재스민 밀크티", fr: "Thé au lait au jasmin", ru: "Жасминовый молочный чай" } },
    ],
  },
  {
    id: "smoothie",
    icon: "🥤",
    items: [
      { id: "s1", price: 30, img: IMG("must-try%2Favocado.jpg"), names: { en: "Avocado Smoothie", vi: "Sinh tố bơ", zh: "牛油果冰沙", ja: "アボカドスムージー", ko: "아보카도 스무디", fr: "Smoothie à l'avocat", ru: "Смузи из авокадо" }, badge: "★", highlight: "Must try" },
      { id: "s2", price: 30, img: IMG("must-try%2Fmango.jpg"), names: { en: "Mango Smoothie", vi: "Sinh tố xoài", zh: "芒果冰沙", ja: "マンゴースムージー", ko: "망고 스무디", fr: "Smoothie à la mangue", ru: "Манговый смузи" }, badge: "★", highlight: "Must try" },
      { id: "s3", price: 25, img: IMG("must-try%2Fmilo-dam.jpg"), names: { en: "Crushed Milo", vi: "Milo dầm đá", zh: "美禄碎冰", ja: "クラッシュドミロ", ko: "크러쉬드 밀로", fr: "Milo glacé", ru: "Майло со льдом" } },
      { id: "s4", price: 25, img: IMG("must-try%2Fda-me-1.jpg"), names: { en: "Tamarind & Arenga", vi: "Đá me hạt đác", zh: "罗望子糖棕", ja: "タマリンド アレンガ", ko: "타마린드 아렝가", fr: "Tamarin & arenga", ru: "Тамаринд с пальмовыми семенами" } },
      { id: "s5", price: 25, img: IMG("must-try%2Fnha-dam.jpg"), names: { en: "Aloe Chia Cooler", vi: "Nha đam hạt chia", zh: "芦荟奇亚籽", ja: "アロエ チア", ko: "알로에 치아", fr: "Aloès & graines de chia", ru: "Алоэ с семенами чиа" } },
      { id: "s6", price: 25, img: IMG("must-try%2Fmatcha.jpg"), names: { en: "Matcha Latte", vi: "Matcha Latte", zh: "抹茶拿铁", ja: "抹茶ラテ", ko: "말차 라떼", fr: "Matcha Latte", ru: "Матча латте" }, highlight: "New" },
    ],
  },
  {
    id: "juice",
    icon: "🍊",
    items: [
      { id: "j1", price: 20, img: IMG("juice%2Fdua.jpg"), names: { en: "Pineapple Juice", vi: "Nước ép dứa", zh: "菠萝汁", ja: "パイナップルジュース", ko: "파인애플 주스", fr: "Jus d'ananas", ru: "Ананасовый сок" } },
      { id: "j2", price: 20, img: IMG("juice%2Fcam.jpg"), names: { en: "Orange Juice", vi: "Nước ép cam", zh: "橙汁", ja: "オレンジジュース", ko: "오렌지 주스", fr: "Jus d'orange", ru: "Апельсиновый сок" } },
      { id: "j3", price: 20, img: IMG("juice%2Fdua-hau.jpg"), names: { en: "Watermelon Juice", vi: "Nước ép dưa hấu", zh: "西瓜汁", ja: "スイカジュース", ko: "수박 주스", fr: "Jus de pastèque", ru: "Арбузный сок" } },
      { id: "j4", price: 20, img: IMG("juice%2Ftay.jpg"), names: { en: "Celery Juice", vi: "Nước ép rau cần", zh: "芹菜汁", ja: "セロリジュース", ko: "셀러리 주스", fr: "Jus de céleri", ru: "Сок сельдерея" } },
      { id: "j5", price: 20, img: IMG("juice%2Fday.jpg"), names: { en: "Passion Fruit", vi: "Nước chanh dây", zh: "百香果汁", ja: "パッションフルーツ", ko: "패션후르츠", fr: "Fruit de la passion", ru: "Маракуйя" } },
      { id: "j6", price: 20, img: IMG("juice%2Fchanh.jpg"), names: { en: "Lemon Juice", vi: "Nước chanh", zh: "柠檬汁", ja: "レモンジュース", ko: "레몬 주스", fr: "Citronnade", ru: "Лимонный сок" } },
    ],
  },
  {
    id: "tea",
    icon: "🍵",
    items: [
      { id: "t1", price: 25, img: IMG("tea%2Ftra-gung.jpg"), names: { en: "Ginger Tea", vi: "Trà gừng", zh: "姜茶", ja: "ジンジャーティー", ko: "생강차", fr: "Thé au gingembre", ru: "Чай с имбирём" } },
      { id: "t2", price: 25, img: IMG("tea%2Ftra-tac.jpg"), names: { en: "Kumquat Tea", vi: "Trà tắc", zh: "金桔茶", ja: "金柑茶", ko: "금귤차", fr: "Thé au kumquat", ru: "Кумкватовый чай" } },
      { id: "t3", price: 25, img: IMG("tea%2Ftra-chanh.jpg"), names: { en: "Lemon Tea", vi: "Trà chanh", zh: "柠檬茶", ja: "レモンティー", ko: "레몬티", fr: "Thé au citron", ru: "Чай с лимоном" } },
      { id: "t4", price: 25, img: IMG("tea%2Ftra-trai-cay.jpg"), names: { en: "Fruit Tea", vi: "Trà trái cây", zh: "水果茶", ja: "フルーツティー", ko: "과일차", fr: "Thé aux fruits", ru: "Фруктовый чай" } },
      { id: "t5", price: 25, img: IMG("tea%2Ftra-mang-cau.jpg"), names: { en: "Soursop Tea", vi: "Trà mãng cầu", zh: "刺果番荔枝茶", ja: "サワーソップティー", ko: "사워솝 차", fr: "Thé au corossol", ru: "Чай из соусепа" } },
      { id: "t6", price: 25, img: IMG("tea%2Ftra-dao-cam-xa.jpg"), names: { en: "Peach Lemongrass", vi: "Trà đào cam sả", zh: "桃子柠檬草茶", ja: "ピーチレモングラス", ko: "복숭아 레몬그라스", fr: "Pêche & citronnelle", ru: "Персик с лемонграссом" } },
      { id: "t7", price: 25, img: IMG("tea%2Ftra-vai.jpg"), names: { en: "Lychee Tea", vi: "Trà vải", zh: "荔枝茶", ja: "ライチティー", ko: "리치 차", fr: "Thé au litchi", ru: "Чай с личи" } },
    ],
  },
];

// translation strings keyed by language code
const I18N = {
  en: {
    nav_menu: "Menu", nav_about: "About", nav_reviews: "Reviews", nav_visit: "Visit", nav_gallery: "Gallery", nav_hours: "Hours",
    hero_eyebrow: "A Vietnamese coffee shop · since 2019",
    hero_title: "The best coffee\nin the neighborhood.",
    hero_sub: "An honest Vietnamese coffee shop. Hand-poured phin one cup at a time, real fruit in every smoothie, and the warmest welcome on the block. Locals call us their morning routine.",
    hero_cta: "View the menu",
    hero_cta2: "Find us",
    cat_coffee: "Coffee", cat_milktea: "Milk Tea", cat_smoothie: "Smoothies", cat_juice: "Juice", cat_tea: "Tea",
    menu_eyebrow: "The Menu", menu_title: "Made fresh, all day.",
    menu_currency: "₫",
    about_eyebrow: "Our Story",
    about_title: "Six years of pulling shots,\nstirring tamarind ice, and\nlearning everyone's order.",
    about_body: "Cafe 39 opened as a single iron table on the sidewalk. Today we still hand-pour the phin, still keep the door open from sunrise, and still know your usual after the second visit. Robusta beans from Đắk Lắk. Real fruit, every juice. Music low enough to think.",
    reviews_eyebrow: "Word of mouth", reviews_title: "What guests say.",
    reviews_more: "Read more on Google",
    visit_eyebrow: "Stop by", visit_title: "Find the front door.",
    visit_dir: "Get directions",
    hours_title: "Hours",
    hours_mf: "Mon – Fri", hours_mf_time: "6:30 – 22:30",
    hours_sat: "Saturday", hours_sat_time: "7:00 – 23:00",
    hours_sun: "Sunday", hours_sun_time: "7:00 – 22:00",
    gallery_eyebrow: "Friends of the house", gallery_title: "Regulars from everywhere.",
    friends_sub: "Drop your customer photos onto the cards — they save here.",
    foot_tag: "Made with phin, condensed milk, and ice.",
    foot_copy: "© Cafe 39. All cups reserved.",
    now_open: "Open now",
    now_closed: "Closed",
    now_opens_at: "Opens at",
    now_closes_at: "Closes at",
    cta_call: "Call",
    cta_zalo: "Zalo",
    cta_order: "Order online",
    cta_call_long: "Call to order",
    cta_zalo_long: "Chat on Zalo",
    search_placeholder: "Search the menu…",
    search_no_results: "Nothing matches that — try another word.",
    stories_eyebrow: "Lately, around the shop",
    owner_eyebrow: "Meet the owner",
    owner_title: "Pulled by hand. Served by name.",
    owner_body: "Six years behind the phin. I learned to roast from my father in Đắk Lắk, opened Cafe 39 with a single iron table on the sidewalk, and have not missed a sunrise since. Tell me your usual — I will remember it.",
    owner_signoff: "— Owner",
    payment_eyebrow: "Cashless welcome",
    payment_title: "Scan to pay.",
    payment_sub: "VietQR, MoMo, ZaloPay — or cash at the counter.",
    promo: "Today: Free phin filter loan with any 2 coffees · ask at the counter",
  },
  vi: {
    nav_menu: "Thực đơn", nav_about: "Câu chuyện", nav_reviews: "Đánh giá", nav_visit: "Ghé thăm", nav_gallery: "Hình ảnh", nav_hours: "Giờ mở cửa",
    hero_eyebrow: "Quán cà phê Việt · từ 2019",
    hero_title: "Cà phê ngon nhất\ntrong khu phố.",
    hero_sub: "Quán cà phê Việt thứ thiệt. Pha phin từng ly, sinh tố trái cây tươi, và nụ cười ấm áp nhất dãy phố. Khách quen gọi tụi mình là thói quen buổi sáng.",
    hero_cta: "Xem thực đơn",
    hero_cta2: "Tìm quán",
    cat_coffee: "Cà Phê", cat_milktea: "Trà Sữa", cat_smoothie: "Sinh Tố", cat_juice: "Nước Ép", cat_tea: "Trà",
    menu_eyebrow: "Thực đơn", menu_title: "Pha tươi, cả ngày.",
    menu_currency: "đ",
    about_eyebrow: "Câu Chuyện",
    about_title: "Sáu năm pha phin,\nquậy đá me, và\nthuộc nằm lòng món của bạn.",
    about_body: "Cafe 39 bắt đầu chỉ với một chiếc bàn sắt trên vỉa hè. Đến nay vẫn pha phin từng ly, vẫn mở cửa từ sớm, và vẫn nhớ món bạn hay gọi sau lần thứ hai. Hạt Robusta từ Đắk Lắk. Trái cây thật, mỗi ly nước ép. Nhạc nhẹ vừa đủ để nghĩ.",
    reviews_eyebrow: "Khách kể", reviews_title: "Khách nói gì về quán.",
    reviews_more: "Xem thêm trên Google",
    visit_eyebrow: "Ghé quán", visit_title: "Tìm cửa trước.",
    visit_dir: "Chỉ đường",
    hours_title: "Giờ Mở Cửa",
    hours_mf: "Thứ 2 – Thứ 6", hours_mf_time: "6:30 – 22:30",
    hours_sat: "Thứ 7", hours_sat_time: "7:00 – 23:00",
    hours_sun: "Chủ Nhật", hours_sun_time: "7:00 – 22:00",
    gallery_eyebrow: "Khách phương xa", gallery_title: "Người quen từ khắp nơi.",
    friends_sub: "Thả ảnh khách vào các thẻ — tự động lưu lại.",
    foot_tag: "Pha bằng phin, sữa đặc, và đá.",
    foot_copy: "© Cafe 39. Mọi ly cà phê được giữ lại.",
    now_open: "Đang mở",
    now_closed: "Đã đóng",
    now_opens_at: "Mở lúc",
    now_closes_at: "Đóng lúc",
    cta_call: "Gọi",
    cta_zalo: "Zalo",
    cta_order: "Đặt online",
    cta_call_long: "Gọi đặt",
    cta_zalo_long: "Chat Zalo",
    search_placeholder: "Tìm món…",
    search_no_results: "Không có món nào khớp — thử từ khác nhé.",
    stories_eyebrow: "Gần đây tại quán",
    owner_eyebrow: "Gặp chủ quán",
    owner_title: "Tay pha. Nhớ tên.",
    owner_body: "Sáu năm sau quầy phin. Học rang từ cha ở Đắk Lắk, mở Cafe 39 với một chiếc bàn sắt vỉa hè, chưa bỏ buổi nào kể từ đó. Bạn hay gọi gì — mình sẽ nhớ.",
    owner_signoff: "— Chủ quán",
    payment_eyebrow: "Thanh toán không tiền mặt",
    payment_title: "Quét để trả.",
    payment_sub: "VietQR, MoMo, ZaloPay — hoặc tiền mặt tại quầy.",
    promo: "Hôm nay: Mượn phin miễn phí khi gọi 2 ly · hỏi tại quầy",
  },
  zh: {
    nav_menu: "菜单", nav_about: "故事", nav_reviews: "评价", nav_visit: "到店", nav_gallery: "画廊", nav_hours: "营业时间",
    hero_eyebrow: "越南咖啡馆 · 自2019年",
    hero_title: "街区最棒的\n一杯咖啡。",
    hero_sub: "地道越南咖啡馆。手冲滤漏一杯一杯来，冰沙都是真果，还有街区最温暖的问候。街坊们的清晨习惯。",
    hero_cta: "查看菜单",
    hero_cta2: "找到我们",
    cat_coffee: "咖啡", cat_milktea: "奶茶", cat_smoothie: "冰沙", cat_juice: "果汁", cat_tea: "茶",
    menu_eyebrow: "菜单", menu_title: "全天新鲜制作。",
    menu_currency: "₫",
    about_eyebrow: "我们的故事",
    about_title: "六年时光,\n冲咖啡,搅罗望子冰,\n记住每位客人的口味。",
    about_body: "Cafe 39 起初只是人行道上的一张铁桌。如今,我们依然手冲滴漏壶,日出便开门,客人来过两次便记住口味。咖啡豆来自得乐省。每一杯果汁,都是真水果。音乐恰好,够你静下心来。",
    reviews_eyebrow: "口口相传", reviews_title: "客人怎么说。",
    reviews_more: "在Google查看更多",
    visit_eyebrow: "到店", visit_title: "找到门牌。",
    visit_dir: "获取路线",
    hours_title: "营业时间",
    hours_mf: "周一 – 周五", hours_mf_time: "6:30 – 22:30",
    hours_sat: "周六", hours_sat_time: "7:00 – 23:00",
    hours_sun: "周日", hours_sun_time: "7:00 – 22:00",
    gallery_eyebrow: "远方的朋友", gallery_title: "来自世界各地的常客。",
    friends_sub: "拖拽客人照片到卡片上 — 自动保存。",
    foot_tag: "以滴漏壶、炼乳和冰制成。",
    foot_copy: "© Cafe 39. 保留所有咖啡。",
    now_open: "营业中",
    now_closed: "已休息",
    now_opens_at: "开门",
    now_closes_at: "打烊",
    cta_call: "致电",
    cta_zalo: "Zalo",
    cta_order: "在线点单",
    cta_call_long: "致电下单",
    cta_zalo_long: "Zalo 聊一聊",
    search_placeholder: "搜索菜单…",
    search_no_results: "没找到匹配的 —— 换个词试试。",
    stories_eyebrow: "店里近况",
    owner_eyebrow: "认识店主",
    owner_title: "手工冲制 · 名字相熟。",
    owner_body: "在咖啡壶后六年。我从父亲那里在得乐省学会烘豆,带着一张铁桌在人行道上开了Cafe 39,从此没错过一个日出。告诉我您常点什么,我会记住。",
    owner_signoff: "— 店主",
    payment_eyebrow: "支持无现金",
    payment_title: "扫码即付。",
    payment_sub: "VietQR、MoMo、ZaloPay —— 或柜台现金。",
    promo: "今日:点两杯咖啡免费借滴漏壶 · 柜台询问",
  },
  ja: {
    nav_menu: "メニュー", nav_about: "ストーリー", nav_reviews: "レビュー", nav_visit: "アクセス", nav_gallery: "ギャラリー", nav_hours: "営業時間",
    hero_eyebrow: "ベトナムカフェ · 2019年から",
    hero_title: "街で一番の\nコーヒー。",
    hero_sub: "本場のベトナムコーヒーを一杯ずつ手淹れ。スムージーはフルーツたっぷり、街一のあったかいもてなしも。地元客の朝の習慣です。",
    hero_cta: "メニューを見る",
    hero_cta2: "お店を探す",
    cat_coffee: "コーヒー", cat_milktea: "ミルクティー", cat_smoothie: "スムージー", cat_juice: "ジュース", cat_tea: "茶",
    menu_eyebrow: "メニュー", menu_title: "一日中、淹れたて。",
    menu_currency: "₫",
    about_eyebrow: "私たちの物語",
    about_title: "六年間、コーヒーを淹れ、\nタマリンドの氷を混ぜ、\nお客様の好みを覚えてきました。",
    about_body: "Cafe 39 は歩道の鉄テーブル一つから始まりました。今も手淹れのフィン、日の出からの開店、二度目で覚える「いつもの」は変わりません。豆はダクラク産。ジュースはすべて本物の果物。思考できるくらいの静かな音楽。",
    reviews_eyebrow: "口コミ", reviews_title: "お客様の声。",
    reviews_more: "Googleでもっと見る",
    visit_eyebrow: "アクセス", visit_title: "玄関までの道。",
    visit_dir: "経路案内",
    hours_title: "営業時間",
    hours_mf: "月 – 金", hours_mf_time: "6:30 – 22:30",
    hours_sat: "土曜日", hours_sat_time: "7:00 – 23:00",
    hours_sun: "日曜日", hours_sun_time: "7:00 – 22:00",
    gallery_eyebrow: "遠くからの友達", gallery_title: "世界中からの常連さん。",
    friends_sub: "お客様とオーナーの写真をドロップ—保存されます。",
    foot_tag: "フィン、練乳、氷でつくりました。",
    foot_copy: "© Cafe 39. 全てのカップを大切に。",
    now_open: "営業中",
    now_closed: "閉店中",
    now_opens_at: "開店",
    now_closes_at: "閉店",
    cta_call: "電話",
    cta_zalo: "Zalo",
    cta_order: "ネット注文",
    cta_call_long: "電話で注文",
    cta_zalo_long: "Zaloでチャット",
    search_placeholder: "メニューを検索…",
    search_no_results: "見つかりません — 別の言葉でお試しを。",
    stories_eyebrow: "最近のお店",
    owner_eyebrow: "オーナーの紹介",
    owner_title: "手淹れ。名前で呼びます。",
    owner_body: "フィンの向こうで六年。父からダクラクで焙煎を学び、歩道に鉄テーブル一つでCafe 39を始め、それから一度も日の出を逃していません。いつものを教えてください — 覚えます。",
    owner_signoff: "— オーナー",
    payment_eyebrow: "キャッシュレス対応",
    payment_title: "スキャンして支払い。",
    payment_sub: "VietQR、MoMo、ZaloPay — もちろん現金もOK。",
    promo: "本日:コーヒー2杯でフィン無料貸出 · カウンターでお声がけください",
  },
  ko: {
    nav_menu: "메뉴", nav_about: "이야기", nav_reviews: "리뷰", nav_visit: "방문", nav_gallery: "갤러리", nav_hours: "영업시간",
    hero_eyebrow: "베트남 카페 · 2019년부터",
    hero_title: "동네 최고의\n커피 한 잔.",
    hero_sub: "진짜 베트남 카페. 핏 자메이커 한 잔씩 직접 내리고, 스무디는 생과일로, 동네 제일 따뜻한 환대까지. 단골들의 아침 루틴이에요.",
    hero_cta: "메뉴 보기",
    hero_cta2: "오시는 길",
    cat_coffee: "커피", cat_milktea: "밀크티", cat_smoothie: "스무디", cat_juice: "주스", cat_tea: "차",
    menu_eyebrow: "메뉴", menu_title: "하루 종일 신선하게.",
    menu_currency: "₫",
    about_eyebrow: "우리의 이야기",
    about_title: "6년 동안 커피를 내리고,\n타마린드 얼음을 젓고,\n모두의 단골 메뉴를 외웠습니다.",
    about_body: "Cafe 39는 인도 위 작은 철제 테이블 하나로 시작했습니다. 지금도 손으로 핀을 내리고, 해 뜰 때 문을 열고, 두 번째 방문이면 늘 드시는 걸 기억합니다. 닥락 로부스타. 모든 주스는 진짜 과일로. 사색하기 좋은 작은 음악.",
    reviews_eyebrow: "입소문", reviews_title: "손님들의 말씀.",
    reviews_more: "Google에서 더 보기",
    visit_eyebrow: "방문", visit_title: "문 앞까지.",
    visit_dir: "길찾기",
    hours_title: "영업시간",
    hours_mf: "월 – 금", hours_mf_time: "6:30 – 22:30",
    hours_sat: "토요일", hours_sat_time: "7:00 – 23:00",
    hours_sun: "일요일", hours_sun_time: "7:00 – 22:00",
    gallery_eyebrow: "멀리서 온 친구들", gallery_title: "세계 곳곳의 단골소님들.",
    friends_sub: "손님과 사장님의 사진을 카드에 떨구세요 — 자동 저장됩니다.",
    foot_tag: "핀, 연유, 얼음으로.",
    foot_copy: "© Cafe 39. 모든 잔을 소중하게.",
    now_open: "영업 중",
    now_closed: "영업 종료",
    now_opens_at: "오픈",
    now_closes_at: "마감",
    cta_call: "전화",
    cta_zalo: "Zalo",
    cta_order: "온라인 주문",
    cta_call_long: "전화 주문",
    cta_zalo_long: "Zalo로 채팅",
    search_placeholder: "메뉴 검색…",
    search_no_results: "검색 결과 없음 — 다른 단어로 시도해 보세요.",
    stories_eyebrow: "최근 가게 소식",
    owner_eyebrow: "사장님 소개",
    owner_title: "직접 내립니다. 이름으로 불러요.",
    owner_body: "핀 뒤에서 6년. 아버지에게 닥락에서 로스팅을 배우고, 인도 위 작은 철제 테이블 하나로 Cafe 39를 열었어요. 그 뒤로 일출을 놓친 적이 없어요. 단골 메뉴를 알려주세요 — 기억해 둘게요.",
    owner_signoff: "— 사장",
    payment_eyebrow: "현금 없이 OK",
    payment_title: "스캔해서 결제.",
    payment_sub: "VietQR, MoMo, ZaloPay — 또는 현장 현금.",
    promo: "오늘: 커피 2잔에 핀 필터 무료 대여 · 카운터에 문의",
  },
  fr: {
    nav_menu: "Carte", nav_about: "Histoire", nav_reviews: "Avis", nav_visit: "Visiter", nav_gallery: "Galerie", nav_hours: "Horaires",
    hero_eyebrow: "Café vietnamien · depuis 2019",
    hero_title: "Le meilleur café\ndu quartier.",
    hero_sub: "Un vrai café vietnamien. Phin passé à la main tasse par tasse, vrais fruits dans chaque smoothie, et l'accueil le plus chaleureux du pâté de maisons. Les habitués en font leur rituel du matin.",
    hero_cta: "Voir la carte",
    hero_cta2: "Nous trouver",
    cat_coffee: "Café", cat_milktea: "Thé au lait", cat_smoothie: "Smoothies", cat_juice: "Jus", cat_tea: "Thé",
    menu_eyebrow: "La carte", menu_title: "Préparés frais, toute la journée.",
    menu_currency: "₫",
    about_eyebrow: "Notre histoire",
    about_title: "Six ans à tirer des cafés,\nremuer la glace au tamarin,\net retenir vos commandes.",
    about_body: "Cafe 39 a commencé avec une seule table en fer sur le trottoir. Aujourd'hui encore, nous infusons le phin à la main, ouvrons dès l'aube, et connaissons votre commande dès la deuxième visite. Grains Robusta de Đắk Lắk. Vrais fruits, chaque jus. Musique assez basse pour penser.",
    reviews_eyebrow: "Bouche à oreille", reviews_title: "Ce que disent les clients.",
    reviews_more: "Voir plus sur Google",
    visit_eyebrow: "Venir", visit_title: "Trouver la porte.",
    visit_dir: "Itinéraire",
    hours_title: "Horaires",
    hours_mf: "Lun – Ven", hours_mf_time: "6:30 – 22:30",
    hours_sat: "Samedi", hours_sat_time: "7:00 – 23:00",
    hours_sun: "Dimanche", hours_sun_time: "7:00 – 22:00",
    gallery_eyebrow: "Amis de la maison", gallery_title: "Des habitués venus de partout.",
    friends_sub: "Glissez les photos des clients sur les cartes — elles sont enregistrées.",
    foot_tag: "Fait au phin, au lait concentré, et à la glace.",
    foot_copy: "© Cafe 39. Toutes tasses réservées.",
    now_open: "Ouvert",
    now_closed: "Fermé",
    now_opens_at: "Ouvre à",
    now_closes_at: "Ferme à",
    cta_call: "Appeler",
    cta_zalo: "Zalo",
    cta_order: "Commander en ligne",
    cta_call_long: "Appeler pour commander",
    cta_zalo_long: "Discuter sur Zalo",
    search_placeholder: "Chercher dans la carte…",
    search_no_results: "Rien ne correspond — essayez un autre mot.",
    stories_eyebrow: "Dernières nouvelles",
    owner_eyebrow: "Le patron",
    owner_title: "Tirées à la main. Servies par votre prénom.",
    owner_body: "Six ans derrière le phin. J'ai appris à torréfier auprès de mon père à Đắk Lắk, ouvert Cafe 39 avec une seule table en fer sur le trottoir, et n'ai pas raté un lever de soleil depuis. Dites-moi votre commande habituelle — je m'en souviendrai.",
    owner_signoff: "— Le patron",
    payment_eyebrow: "Sans contact bienvenu",
    payment_title: "Scannez pour payer.",
    payment_sub: "VietQR, MoMo, ZaloPay — ou espèces au comptoir.",
    promo: "Aujourd'hui : Prêt de phin gratuit pour 2 cafés · demandez au comptoir",
  },
  ru: {
    nav_menu: "Меню", nav_about: "О нас", nav_reviews: "Отзывы", nav_visit: "Найти нас", nav_gallery: "Друзья", nav_hours: "Часы работы",
    hero_eyebrow: "Вьетнамская кофейня · с 2019 года",
    hero_title: "Лучший кофе\nв районе.",
    hero_sub: "Настоящая вьетнамская кофейня. Завариваем фин чашка за чашкой, в каждом смузи — настоящие фрукты, а встречаем теплее всех на улице. Местные приходят сюда каждое утро.",
    hero_cta: "Открыть меню",
    hero_cta2: "Найти нас",
    cat_coffee: "Кофе", cat_milktea: "Молочный чай", cat_smoothie: "Смузи", cat_juice: "Соки", cat_tea: "Чай",
    menu_eyebrow: "Меню", menu_title: "Свежее весь день.",
    menu_currency: "₫",
    about_eyebrow: "Наша история",
    about_title: "Шесть лет варим кофе,\nмешаем тамариндовый лёд\nи помним заказ каждого.",
    about_body: "Cafe 39 начался с одного железного столика на тротуаре. И сегодня мы по-прежнему варим фин вручную, открываемся на рассвете и со второго визита помним ваш заказ. Зёрна робусты из Даклак. Настоящие фрукты — в каждом соке. Музыка тихая, есть где подумать.",
    reviews_eyebrow: "Сарафанное радио", reviews_title: "Что говорят гости.",
    reviews_more: "Больше отзывов в Google",
    visit_eyebrow: "Зайти", visit_title: "Найти нашу дверь.",
    visit_dir: "Маршрут",
    hours_title: "Часы работы",
    hours_mf: "Пн – Пт", hours_mf_time: "6:30 – 22:30",
    hours_sat: "Суббота", hours_sat_time: "7:00 – 23:00",
    hours_sun: "Воскресенье", hours_sun_time: "7:00 – 22:00",
    gallery_eyebrow: "Друзья дома", gallery_title: "Завсегдатаи со всего света.",
    friends_sub: "Перетащите фото гостей на карточки — они сохранятся.",
    foot_tag: "С фином, сгущёнкой и льдом.",
    foot_copy: "© Cafe 39. Все чашки сохранены.",
    now_open: "Открыто",
    now_closed: "Закрыто",
    now_opens_at: "Открывается в",
    now_closes_at: "Закрывается в",
    cta_call: "Позвонить",
    cta_zalo: "Zalo",
    cta_order: "Заказ онлайн",
    cta_call_long: "Позвонить и заказать",
    cta_zalo_long: "Чат в Zalo",
    search_placeholder: "Поиск по меню…",
    search_no_results: "Ничего не найдено — попробуйте другое слово.",
    stories_eyebrow: "В кофейне на днях",
    owner_eyebrow: "Хозяин",
    owner_title: "Заварено вручную. Подано по имени.",
    owner_body: "Шесть лет за фином. Учился обжаривать у отца в Даклак, открыл Cafe 39 с одного железного столика на тротуаре и с тех пор не пропустил ни одного восхода. Расскажите, что обычно берёте — запомню.",
    owner_signoff: "— Хозяин",
    payment_eyebrow: "Безнал приветствуется",
    payment_title: "Сканируй и плати.",
    payment_sub: "VietQR, MoMo, ZaloPay — или наличные на кассе.",
    promo: "Сегодня: бесплатный фин на дом при заказе 2 кофе · спросите на кассе",
  },
};

const LANGS = [
  { code: "en", label: "English", flag: "🇬🇧" },
  { code: "vi", label: "Tiếng Việt", flag: "🇻🇳" },
  { code: "zh", label: "中文", flag: "🇨🇳" },
  { code: "ja", label: "日本語", flag: "🇯🇵" },
  { code: "ko", label: "한국어", flag: "🇰🇷" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
  { code: "ru", label: "Русский", flag: "🇷🇺" },
];

// PLACEHOLDER REVIEWS — replace with real Google reviews
const REVIEWS = [
  {
    name: "Linh N.",
    stars: 5,
    date: "2 weeks ago",
    body: { en: "Best salt coffee in the district. Owner remembers my drink and always slips an extra biscuit on the saucer. Stayed for 3 hours, nobody rushed me.", vi: "Cà phê muối ngon nhất khu này. Chủ quán nhớ luôn món tôi hay gọi, lúc nào cũng kèm thêm cái bánh quy. Ngồi 3 tiếng không ai giục.", zh: "全区最好喝的海盐咖啡。老板记得我的常点,总会多放一块小饼干。坐了三小时也没人催。", ja: "この地区で一番のソルトコーヒー。オーナーが私の好みを覚えていて、いつもビスケットをサービスしてくれる。3時間いても誰も急かさない。", ko: "이 동네 최고의 솔트 커피. 사장님이 제 단골 메뉴를 기억하시고 늘 비스킷을 더 얹어주세요. 3시간 있어도 아무도 재촉하지 않아요.", fr: "Le meilleur café salé du quartier. Le patron se souvient de ma commande et glisse toujours un biscuit en plus. Resté 3 heures, personne ne m'a pressé.", ru: "Лучший кофе с солью в районе. Хозяин помнит мой заказ и всегда подкладывает печенье на блюдце. Просидел три часа — никто не торопил." },
  },
  {
    name: "Marc D.",
    stars: 5,
    date: "1 month ago",
    body: { en: "Wandered in for a coconut coffee on a humid afternoon. Left with a new favorite spot. The avocado smoothie is unreal — thick, just sweet enough, big glass.", vi: "Ghé vào uống cà phê dừa giữa trưa nóng. Ra về kèm theo một quán tủ mới. Sinh tố bơ siêu đỉnh — đặc, ngọt vừa, ly to.", zh: "湿热的午后随便走进来点了杯椰子咖啡,结果发现新爱店。牛油果冰沙超棒 —— 浓稠、甜度刚好、大杯。", ja: "蒸し暑い午後にふらりと寄ってココナッツコーヒーを。新しいお気に入りに。アボカドスムージーは絶品 — 濃厚、甘さ控えめ、大ぶり。", ko: "후덥지근한 오후에 코코넛 커피 한 잔 하러 들렀다가 단골이 됐어요. 아보카도 스무디 정말 끝내줘요 — 진하고 적당히 달고, 잔도 커요.", fr: "Entré pour un café coco un après-midi humide. Reparti avec un nouveau spot favori. Le smoothie à l'avocat est dingue — épais, juste assez sucré, grand verre.", ru: "Зашёл за кокосовым кофе душным днём. Ушёл с новым любимым местом. Смузи из авокадо невероятный — густой, в меру сладкий, большой стакан." },
  },
  {
    name: "Hana K.",
    stars: 5,
    date: "3 weeks ago",
    body: { en: "Tiny place, big personality. Try the bạc xỉu. Cash only at the counter — bring small notes. Plug points by the window seats, decent wifi.", vi: "Quán nhỏ mà gu lắm. Thử bạc xỉu nhé. Quầy chỉ nhận tiền mặt — mang tiền lẻ. Có ổ điện gần cửa sổ, wifi ổn.", zh: "小店气场足。一定试试 bạc xỉu。柜台只收现金 —— 带些零钱。窗边有插座,wifi 还行。", ja: "小さなお店だけど個性十分。バクシウを試して。レジは現金のみ — 小銭を忘れずに。窓際にコンセントあり、Wi-Fiも普通。", ko: "작지만 매력 가득한 카페. 박씨우 꼭 드셔보세요. 계산대는 현금만 — 잔돈 챙기세요. 창가에 콘센트 있고, 와이파이도 괜찮아요.", fr: "Petit lieu, gros caractère. Essayez le bạc xỉu. Comptoir en espèces — prévoir de la monnaie. Prises près des fenêtres, wifi correct.", ru: "Маленькое место, большой характер. Попробуйте бакщиу. На кассе только наличные — берите мелкие купюры. У окна есть розетки, Wi-Fi нормальный." },
  },
  {
    name: "Tuấn P.",
    stars: 4,
    date: "2 months ago",
    body: { en: "Solid neighborhood coffee. Phin coffee is excellent, smoothies fresh. Gets busy 8–9am, plan accordingly. Staff are kind to a fault.", vi: "Cà phê xóm chuẩn bài. Phin pha rất ngon, sinh tố tươi. 8-9h sáng đông, canh giờ. Nhân viên thì khỏi chê.", zh: "扎实的街区咖啡。滴漏咖啡很棒,冰沙新鲜。早上 8-9 点会很挤,记得错峰。店员特别热情。", ja: "近所のしっかりしたコーヒー店。フィンコーヒーは絶品、スムージーもフレッシュ。朝8-9時は混むので時間を考えて。店員さんは親切すぎるくらい。", ko: "동네 카페로 든든해요. 핀 커피 훌륭하고 스무디도 신선. 8-9시는 붐비니 시간 계획 잘하세요. 직원분들 정말 친절해요.", fr: "Solide café de quartier. Le phin est excellent, smoothies frais. Bondé entre 8h et 9h, à anticiper. Personnel adorable.", ru: "Крепкая местная кофейня. Фин отличный, смузи свежие. С 8 до 9 утра шумно — планируйте. Персонал — само радушие." },
  },
  {
    name: "Sophie L.",
    stars: 5,
    date: "1 week ago",
    body: { en: "Came back three days in a row. Owner taught me the difference between Robusta and Arabica. Salt coffee converted my friend who 'doesn't like coffee.'", vi: "Ba ngày liên tiếp ghé. Chủ quán dạy mình phân biệt Robusta với Arabica. Cà phê muối làm đứa bạn 'không thích cà phê' phải đổi ý.", zh: "连续三天去。老板教我分辨罗布斯塔和阿拉比卡。海盐咖啡让我那个'不爱咖啡'的朋友彻底改观。", ja: "三日連続で通いました。オーナーがロブスタとアラビカの違いを教えてくれた。ソルトコーヒーで「コーヒー苦手」な友人が改宗。", ko: "삼 일 연속 방문. 사장님이 로부스타랑 아라비카 차이를 알려주셨어요. 솔트 커피로 '커피 안 좋아하는' 친구가 입덕했어요.", fr: "Revenu trois jours d'affilée. Le patron m'a expliqué la différence Robusta/Arabica. Le café salé a converti mon ami qui 'n'aime pas le café'.", ru: "Возвращался три дня подряд. Хозяин объяснил разницу между робустой и арабикой. Кофе с солью обратил в кофейную веру друга, который «не любит кофе»." },
  },
];

const GOOGLE_MAPS_URL = "https://maps.app.goo.gl/Rcv6SCwcpaSDT8yn9";
const GOOGLE_MAPS_EMBED = "https://maps.google.com/maps?q=Cafe%2039%20Vietnam&t=&z=15&ie=UTF8&iwloc=&output=embed";

// Contact details — replace with real values
const CONTACT = {
  phone: "+84 28 1234 5678",
  phoneRaw: "+842812345678",
  zalo: "+842812345678",     // Zalo uses the same phone
  shopeeFood: "https://shopeefood.vn/",
  grabFood: "https://food.grab.com/vn/en",
  instagram: "https://instagram.com/cafe39",
  facebook: "https://facebook.com/cafe39",
};

// Operating hours per weekday (0=Sun, 6=Sat). 24h "HH:MM".
const HOURS = {
  0: { open: "07:00", close: "22:00", label: "Sun" },
  1: { open: "06:30", close: "22:30", label: "Mon" },
  2: { open: "06:30", close: "22:30", label: "Tue" },
  3: { open: "06:30", close: "22:30", label: "Wed" },
  4: { open: "06:30", close: "22:30", label: "Thu" },
  5: { open: "06:30", close: "22:30", label: "Fri" },
  6: { open: "07:00", close: "23:00", label: "Sat" },
};

// Banking / wallet QR codes for cashless payment (placeholder QR images)
const PAYMENT = [
  { id: "vietqr",  label: "VietQR",   sub: "Any Vietnamese bank",  color: "#d52b1e" },
  { id: "momo",    label: "MoMo",     sub: "MoMo wallet",          color: "#a50064" },
  { id: "zalopay", label: "ZaloPay",  sub: "ZaloPay wallet",       color: "#0068ff" },
];

window.CONTACT = CONTACT;
window.HOURS = HOURS;
window.PAYMENT = PAYMENT;

window.MENU = MENU;
window.I18N = I18N;
window.LANGS = LANGS;
window.REVIEWS = REVIEWS;
window.GOOGLE_MAPS_URL = GOOGLE_MAPS_URL;
window.GOOGLE_MAPS_EMBED = GOOGLE_MAPS_EMBED;

// Customer + owner photo wall — placeholder entries. Each renders as a polaroid
// with an <image-slot> the owner drops a real photo into. Names/flags are placeholder;
// edit them inline or replace this array.
const FRIENDS = [
  { id: "f1", flag: "🇫🇷", name: "Marc & owner",   date: "MAR 24", placeholder: "Drop photo · Marc + owner" },
  { id: "f2", flag: "🇯🇵", name: "Hana & owner",   date: "APR 11", placeholder: "Drop photo · Hana + owner" },
  { id: "f3", flag: "🇰🇷", name: "Ji-woo & crew",  date: "JAN 03", placeholder: "Drop photo · Ji-woo + crew" },
  { id: "f4", flag: "🇺🇸", name: "Sophie & owner", date: "MAY 19", placeholder: "Drop photo · Sophie + owner" },
  { id: "f5", flag: "🇨🇳", name: "Wei & friends",  date: "FEB 08", placeholder: "Drop photo · Wei + friends" },
  { id: "f6", flag: "🇬🇧", name: "James & owner",  date: "APR 02", placeholder: "Drop photo · James + owner" },
  { id: "f7", flag: "🇩🇪", name: "Anna & owner",   date: "JUN 14", placeholder: "Drop photo · Anna + owner" },
  { id: "f8", flag: "🇦🇺", name: "Liam & crew",    date: "SEP 21", placeholder: "Drop photo · Liam + crew" },
];
window.FRIENDS = FRIENDS;
